name: flutter_injections
description: Elevate your project's dependency management with this versatile Flutter package. Say goodbye to the limitations of context and unlock the ability to seamlessly create dependencies for modules. Simplify your project's structure and enhance your development process with this powerful tool
version: 1.1.0
homepage: https://gabul.dev
repository: https://github.com/gabuldev/flutter_injections
issue_tracker: https://github.com/gabuldev/flutter_injections/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

topics:
  - dependency
  - di
  - injection
 
